###
GET http://localhost:4000/users/
token: autenticado

###
GET http://localhost:4000/users/1
token: autenticado

###
POST http://localhost:4000/users/
token: autenticado
Content-Type: application/json

{
	"name": "Frank",
	"email": "user@mail.com",
	"age": 36,
	"active": true
}