###
GET http://localhost:3000/files

###
POST http://localhost:3000/files/uploadImage/1efe88a1-dce8-4b2a-b031-db3ffcdeaee5
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< binary data >
--boundary123--
